In [2]:
import os
import sys
sys.path.append(os.path.abspath(".."))
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from etl.extractors import extract_data

In [3]:
df=extract_data("../data/raw/ebay_scraped.csv")

2026-03-25 18:03:03,405 - etl.extractors -INFO - Loaded 96 rows and 7 columns

In [4]:
df.head()

,Row_ID,Order_ID,Order_Date,Segment,Region,Product_Name,Sales
0,1,CA-2026-369326,12/06/2025,Home Office,East,JHK Ergonomic Mesh Office Chair Adjustable Hea...,69.99
1,2,CA-2026-426764,22/04/2025,Consumer,East,"Executive Office Ergonomic Chair, Computer Cha...",120.00
2,3,CA-2026-712456,22/11/2025,Corporate,South,Ergonomic Mesh Office Chair Adjustable Headres...,79.99
3,4,CA-2026-865155,30/06/2025,Home Office,Central,Marsail Ergonomic Office Desk Chair with High ...,99.00
4,5,CA-2026-415286,19/02/2026,Consumer,South,Sleekform Kneeling Chair Ergonomic Office Desk...,65.09

In [5]:
df.describe()

          Row_ID       Sales
count  96.000000   96.000000
mean   48.500000  129.840104
std    27.856777  108.895606
min     1.000000   10.200000
25%    24.750000   65.067500
50%    48.500000   91.820000
75%    72.250000  171.445000
max    96.000000  629.100000

In [6]:
df.dtypes

Row_ID            int64
Order_ID         object
Order_Date       object
Segment          object
Region           object
Product_Name     object
Sales           float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Row_ID        96 non-null     int64
 1   Order_ID      96 non-null     object
 2   Order_Date    96 non-null     object
 3   Segment       96 non-null     object
 4   Region        96 non-null     object
 5   Product_Name  96 non-null     object
 6   Sales         96 non-null     float64
dtypes: float64(1), int64(1), object(5)
memory usage: 5.4+ KB

In [8]:
df.duplicated().sum()

np.int64(0)